# Generated by Django 2.0 on 2019-01-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=100, verbose_name='number')),
                ('volume', models.IntegerField(verbose_name='volume')),
                ('cost', models.IntegerField(verbose_name='cost')),
                ('building_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_number', to='dorm.Building')),
            ],
        ),
    ]
