# Generated by Django 2.0 on 2019-01-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0005_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='building_number',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
