# Generated by Django 2.0 on 2019-01-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0006_auto_20190109_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=100, verbose_name='number')),
                ('high', models.IntegerField(default=0, verbose_name='high')),
                ('room', models.IntegerField(default=0, verbose_name='room')),
                ('begintime', models.DateTimeField(null=True, verbose_name='begintime')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=100, verbose_name='number')),
                ('volume', models.IntegerField(default=0, verbose_name='volume')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
                ('building_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_number', to='dorm.Building')),
            ],
        ),
    ]
