# Generated by Django 2.0 on 2019-01-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0007_building_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=100, verbose_name='number')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('sex', models.CharField(default='', max_length=100, verbose_name='sex')),
                ('nation', models.CharField(default='', max_length=100, verbose_name='nation')),
                ('major', models.CharField(default='', max_length=100, verbose_name='major')),
                ('class_grade', models.CharField(default='', max_length=100, verbose_name='class_grade')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='phone')),
                ('room_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_number', to='dorm.Room')),
            ],
        ),
    ]
