# Generated by Django 2.0 on 2019-01-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0008_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='number',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
    ]
