# Generated by Django 2.0 on 2019-01-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0009_auto_20190110_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='begintime',
            field=models.DateField(null=True, verbose_name='begintime'),
        ),
    ]
