# Generated by Django 2.0 on 2019-01-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0011_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='free',
            field=models.IntegerField(default=0, verbose_name='free'),
        ),
    ]
