# Generated by Django 2.0 on 2019-01-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0012_room_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='sex',
            field=models.CharField(default='', max_length=100, verbose_name='sex'),
        ),
    ]
